server:
  port: 8011

spring:
  application:
    name: service1 #스프링 컨피그의 디렉토리명 과 일치해야 함
  profiles:
    active:
      default

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true # 유레카 서비스에 등록 여부
    fetch-registry: true
    registryFetchIntervalSeconds: 5 # eureka에게 서비스 정보를 가져오는 주기
    disable-delta: true # eureka에게 서비스 정보를 가져올때 변경된 내용만 가져온다. (false로 하면 전체를 가져오기에 대역폭 낭비이다.)
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
        
        
resilience4j:
    circuitbreaker:
        configs:
            default:
                slidingWindowSize: 3
                failureRateThreshold: 80

        instances:
            garden:
                baseConfig: default
                